repair/cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:usluga_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:usluga_id>/',
         views.cart_remove,
         name='cart_remove'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repair/repair/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('statistic/', include('analyzer.urls', namespace='analyzer')),
    path('', include('shop.urls', namespace='shop')),
    path('auth/', include('login.urls', namespace='login')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repair/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('news/', views.news),
    path('news/news_show/<int:id>', views.news_show, name='news_show'),
    path('about/', views.about),
    path('policy/', views.policy),
    path('vacancies/', views.vacancies),
    path('coupons/', views.coupons),
    path('faq/', views.faq),
    path('<int:id>', views.usluga_detail,
         name='usluga_detail'),
    path("create/", views.usluga_create),
    path("edit/<int:id>/", views.usluga_edit),
    path("delete/<int:id>/", views.usluga_delete),
    path('reviews/', views.review, name='reviews'),

    path('', views.usluga_list, name='usluga_list'),
    path('<str:usluga_genre_name>/', views.usluga_list,
         name='usluga_list_by_genre'),
]

repair/shop/models.py
from django.db import models
from typing import List
from django.urls import reverse

from login.models import CustomUser


class Author(models.Model):
    name = models.CharField(max_length=200,
                            help_text='Enter author name')

    def get_absolute_url(self):
        return reverse('shop:author-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=200,
                            help_text='Enter genre name')

    def get_absolute_url(self):
        return reverse('shop:usluga_list_by_genre', args=[str(self.name)])

    def __str__(self):
        return self.name


class Usluga(models.Model):
    title = models.CharField(max_length=200,
                             help_text='Enter usluga title')
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    description = models.CharField(max_length=200,
                                   help_text='Enter usluga description', default='unknown')

    image = models.ImageField(upload_to='usluga/%Y/%m/%d', blank=True)
    quantity = models.IntegerField()
    purchase_count = models.PositiveIntegerField(default=0)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    cost = models.PositiveIntegerField()
    LOAN_STATUS = (
        ('A', 'available'),
        ('U', 'unavailable')
    )
    status = models.CharField(max_length=1,
                              choices=LOAN_STATUS,
                              help_text="units of product")

    def get_absolute_url(self):
        return reverse('shop:usluga_detail', args=[str(self.id)])

    def __str__(self):
        return self.title


class Client(models.Model):
    first_name = models.CharField(max_length=200,
                                  help_text='Enter first name')
    last_name = models.CharField(max_length=200,
                                 help_text='Enter last name')
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone_number = models.CharField(max_length=50,
                                    help_text='Enter phone number')

    def get_absolute_url(self):
        return reverse('client-detail', args=[str(self.id)])

    def __str__(self):
        return '{0}, {1}'.format(self.first_name, self.last_name)


class Post(models.Model):
    title = models.CharField(max_length=255, blank=False)
    short_description = models.TextField(blank=False)
    description = models.TextField(blank=False)
    image = models.ImageField(upload_to="static/images/posts/")

    def __str__(self):
        return self.title


class Review(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

repair/shop/forms.py
from django import forms
from .models import Usluga, Review


class UslugaForm(forms.ModelForm):
    class Meta:
        model = Usluga
        fields = ['title', 'author', 'description', 'image', 'genre', 'cost']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('content',)

repair/shop/views.py
import requests
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseNotFound
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect

from cart.forms import CartAddUslugaForm
from .forms import UslugaForm, ReviewForm
from .models import Usluga, Genre, Author, Post, Review


def usluga_list(request, usluga_genre_name=None):
    genre = None
    genres = Genre.objects.all()
    uslugas = Usluga.objects.all()
    sort_t = request.GET.get('sort')

    if (usluga_genre_name):
        genre_ = get_object_or_404(Genre, name=usluga_genre_name)
        uslugas = uslugas.filter(genre=genre_)

    if (str(sort_t) == 'ascending'):
        uslugas = uslugas.order_by('cost')
    elif (str(sort_t) == 'descending'):
        uslugas = uslugas.order_by('-cost')
    elif (str(sort_t) == 'ascendingcount'):
        uslugas = uslugas.order_by('purchase_count')
    elif (str(sort_t) == 'descendingcount'):
        uslugas = uslugas.order_by('-purchase_count')
    return render(request,
                  'shop/usluga/list.html',
                  {'genre': genre, 'genres': genres, 'uslugas': uslugas})


def usluga_detail(request, id):
    usluga = get_object_or_404(Usluga, id=id)
    cart_usluga_form = CartAddUslugaForm()

    joke = requests.get('https://official-joke-api.appspot.com/jokes/programming/random').json()[0]

    return render(request,
                  'shop/usluga/detail.html',
                  {'usluga': usluga, 'cart_usluga_form': cart_usluga_form,
                   'joke': joke['setup'] + joke['punchline']})


def usluga_create(request):
    if not request.user.is_staff:
        raise PermissionDenied("Net dostupa")

    print(1234567)

    form = UslugaForm()

    if request.method == "POST":
        usluga = Usluga.objects.create(title=request.POST.get('title'),
                                       author=Author.objects.get(id=request.POST.get('author')),
                                       cost=request.POST.get('cost'),
                                       genre=Genre.objects.get(id=request.POST.get('genre')),
                                       quantity=0,
                                       description=request.POST.get('description'),
                                       image=request.POST.get('image'))

        usluga.save()
    else:
        return render(request, "shop/usluga/create.html", {"form": form})
    return HttpResponseRedirect("/")


# изменение данных в бд
def usluga_edit(request, id):
    if not request.user.is_staff:
        raise PermissionDenied("Net dostupa")

    try:
        usluga = Usluga.objects.get(id=id)

        form = UslugaForm(initial={'title': usluga.title, 'author': usluga.author,
                                   'cost': usluga.cost, 'genre': usluga.genre,
                                   'description': usluga.description, 'image': usluga.image})

        if request.method == "POST":
            usluga.title = request.POST.get('title')
            print(request.POST.get('title'))
            usluga.author = Author.objects.get(id=request.POST.get('author'))
            usluga.cost = request.POST.get('cost')
            usluga.genre = Genre.objects.get(id=request.POST.get('genre'))
            usluga.quantity = 0
            usluga.description = request.POST.get('description')
            usluga.image = request.FILES.get('image')
            usluga.save()
            return HttpResponseRedirect("/")
        else:
            return render(request, "shop/usluga/edit.html", {"usluga": usluga, 'form': form})
    except usluga.DoesNotExist:
        return HttpResponseNotFound("<h2>usluga not found</h2>")


# удаление данных из бд
def usluga_delete(request, id):
    if not request.user.is_staff:
        raise PermissionDenied("Net dostupa")

    try:
        usluga = Usluga.objects.get(id=id)
        usluga.delete()
        return HttpResponseRedirect("/")
    except usluga.DoesNotExist:
        return HttpResponseNotFound("<h2>usluga not found</h2>")


def review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('shop/reviews.html')
    else:
        form = ReviewForm()

    reviews = Review.objects.all()
    current_user = request.user
    return render(request, 'shop/reviews.html', {'form': form, 'reviews': reviews, 'current_user': current_user})


def news_show(request, id):
    post = get_object_or_404(Post, id=id)
    return render(request, 'shop/news_show.html', {'post': post})


def news(request):
    lst = Post.objects.all()
    return render(request, 'shop/news.html', context={'news_list': lst})


def about(request):
    return render(request, 'shop/about.html')


def policy(request):
    return render(request, 'shop/policy.html')


def vacancies(request):
    return render(request, 'shop/vacancies.html')


def coupons(request):
    return render(request, 'shop/coupons.html')


def faq(request):
    return render(request, 'shop/faq.html')

repair/shop/templates/shop/usluga/create.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Edit</title>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <title>Edit</title>
    </head>
    <body>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save" >
        </form>
    </body>
    </html>
</html>

repair/shop/templates/shop/usluga/detail.html
{% extends "shop/base.html" %}
{% block title %}
{{ usluga.title }}
{% endblock %}
{% block content %}
<div class="usluga-detail">
    <img src="{% if usluga.image %}{{ usluga.image.url }}{% else %}
    {% endif %}">
    <h1>{{ usluga.title }}</h1>
    <h2>
        <a href="{{ usluga.genre.get_absolute_url }}">{{usluga.genre }}</a>
    </h2>
    <p class="cost">{{ usluga.cost }}</p>
    {%if user.is_authenticated%}
    <form action="{% url 'cart:cart_add' usluga.id %}" method="post">
        {{ cart_usluga_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
    </form>
    {%endif%}
    
    {{ usluga.summary|linebreaks }}
    {%if user.is_staff%}
    <td><a href="edit/{{usluga.id}}/">Edit</a> | <a href="delete/{{usluga.id}}/">Remove</a></td>
    {%endif%}
    <div class="bottom-right">
        <p>{{ joke }}</p>
    </div>
    

    
</div>
{% endblock %}

repair/shop/templates/shop/usluga/edit.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Edit</title>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <title>Edit</title>
    </head>
    <body>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save" >
        </form>
    </body>
    </html>
</html>

repair/shop/templates/shop/usluga/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if genre %}{{ genre.name }}{% else %}Ремонт одежды и обуви{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
    <h3>Вид услуги</h3>
    <ul>
        <li {% if not genre %}class="selected"{% endif %}>
            <a href="{% url 'shop:usluga_list' %}">All</a>
        </li>
        {% for c in genres %}
        <li {% if genre.name == c.name %}class="selected" {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div id="main" class="usluga-list">
    <h1>{% if genre %}{{ genre.name }}{% else %}Услуги{% endif %}
        {% if user.is_staff %}
        <a href="/create/">Create</a>
        {% endif %}
        {%if user.is_superuser%}
        <a href="/statistic/">Stats</a>
        {%endif%}
        <form action="{{ request.get_full_path }}" method="get">
            <button type="submit" name="sort" value="ascending">Отсортировать по возрастанию цены</button>
            <button type="submit" name="sort" value="descending">Отсортировать по убыванию цены</button>
            <button type="submit" name="sort" value="descendingcount">Отсортировать по возрастанию продаж</button>
            <button type="submit" name="sort" value="ascendingcount">Отсортировать по убыванию продаж</button>
        </form>
    </h1>
    {% for usluga in uslugas %}
    <div class="item">
        <a href="{{ usluga.get_absolute_url }}">
            <img src="{% if usluga.image %}{{ usluga.image.url }}{%else %}{% static 'img/no_image.png' %}{% endif %}">
        </a>
        <a href="{{ usluga.get_absolute_url }}">{{ usluga.title }}</a>
        <br>
        {{ usluga.cost }}
    </div>

    {% endfor %}
</div>
{% endblock %}