repair/cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:usluga_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:usluga_id>/',
         views.cart_remove,
         name='cart_remove'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repair/order/urls.py
from . import views
from django.urls import path

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

repair/repair/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('statistic/', include('analyzer.urls', namespace='analyzer')),
    path('', include('shop.urls', namespace='shop')),
    path('auth/', include('login.urls', namespace='login')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repair/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('news/', views.news),
    path('news/news_show/<int:id>', views.news_show, name='news_show'),
    path('about/', views.about),
    path('policy/', views.policy),
    path('vacancies/', views.vacancies),
    path('coupons/', views.coupons),
    path('faq/', views.faq),
    path('<int:id>', views.usluga_detail,
         name='usluga_detail'),
    path("create/", views.usluga_create),
    path("edit/<int:id>/", views.usluga_edit),
    path("delete/<int:id>/", views.usluga_delete),
    path('reviews/', views.review, name='reviews'),

    path('', views.usluga_list, name='usluga_list'),
    path('<str:usluga_genre_name>/', views.usluga_list,
         name='usluga_list_by_genre'),
]

repair/cart/models.py
from django.db import models

# Create your models here.

repair/cart/forms.py
from django import forms

USLUGA_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddUslugaForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=USLUGA_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

repair/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Usluga
from .cart import Cart
from .forms import CartAddUslugaForm
from django.core.exceptions import PermissionDenied

@require_POST
def cart_add(request, usluga_id):
    if not request.user.is_authenticated:
        raise PermissionDenied("Net dostupa")

    cart = Cart(request)
    usluga = get_object_or_404(Usluga, id=usluga_id)
    form = CartAddUslugaForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(usluga=usluga,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, usluga_id):
    if not request.user.is_authenticated:
        raise PermissionDenied("Net dostupa")

    cart = Cart(request)
    usluga = get_object_or_404(Usluga, id=usluga_id)
    cart.remove(usluga)
    return redirect('cart:cart_detail')

def cart_detail(request):
    if not request.user.is_authenticated:
        raise PermissionDenied("Net dostupa")
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

repair/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Usluga</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with usluga=item.usluga %}
                <tr>
                    <td>
                        <a href="{{ usluga.get_absolute_url }}">
                            <img src="
                                {% if usluga.image %}
                                    {{ usluga.image.url }}
                                {% else %}
                                    {% static 'img/no_image.png' %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ usluga.title }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:cart_remove' usluga.id %}">Remove</a></td>
                    <td class="num">{{ item.cost }}</td>
                    <td class="num">{{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'shop:usluga_list' %}" class="button light">Continue shopping</a>
        <a href="{% url 'order:order_create' %}" class="button">
            Checkout
        </a>
    </p>
{% endblock %}