repair/cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:usluga_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:usluga_id>/',
         views.cart_remove,
         name='cart_remove'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repair/login/urls.py
from . import views
from django.urls import path

app_name = 'login'

urlpatterns = [
    path('register/', views.RegisterFormView.as_view(), name = 'register'),
    path('login/', views.LoginFormView.as_view(), name = 'login'),
    path('logout/', views.LogoutView.as_view(), name = 'logout')
]

repair/repair/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('statistic/', include('analyzer.urls', namespace='analyzer')),
    path('', include('shop.urls', namespace='shop')),
    path('auth/', include('login.urls', namespace='login')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

repair/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('news/', views.news),
    path('news/news_show/<int:id>', views.news_show, name='news_show'),
    path('about/', views.about),
    path('policy/', views.policy),
    path('vacancies/', views.vacancies),
    path('coupons/', views.coupons),
    path('faq/', views.faq),
    path('<int:id>', views.usluga_detail,
         name='usluga_detail'),
    path("create/", views.usluga_create),
    path("edit/<int:id>/", views.usluga_edit),
    path("delete/<int:id>/", views.usluga_delete),
    path('reviews/', views.review, name='reviews'),

    path('', views.usluga_list, name='usluga_list'),
    path('<str:usluga_genre_name>/', views.usluga_list,
         name='usluga_list_by_genre'),
]

repair/shop/models.py
from django.db import models
from typing import List
from django.urls import reverse

from login.models import CustomUser


class Author(models.Model):
    name = models.CharField(max_length=200,
                            help_text='Enter author name')

    def get_absolute_url(self):
        return reverse('shop:author-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=200,
                            help_text='Enter genre name')

    def get_absolute_url(self):
        return reverse('shop:usluga_list_by_genre', args=[str(self.name)])

    def __str__(self):
        return self.name


class Usluga(models.Model):
    title = models.CharField(max_length=200,
                             help_text='Enter usluga title')
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    description = models.CharField(max_length=200,
                                   help_text='Enter usluga description', default='unknown')

    image = models.ImageField(upload_to='usluga/%Y/%m/%d', blank=True)
    quantity = models.IntegerField()
    purchase_count = models.PositiveIntegerField(default=0)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    cost = models.PositiveIntegerField()
    LOAN_STATUS = (
        ('A', 'available'),
        ('U', 'unavailable')
    )
    status = models.CharField(max_length=1,
                              choices=LOAN_STATUS,
                              help_text="units of product")

    def get_absolute_url(self):
        return reverse('shop:usluga_detail', args=[str(self.id)])

    def __str__(self):
        return self.title


class Client(models.Model):
    first_name = models.CharField(max_length=200,
                                  help_text='Enter first name')
    last_name = models.CharField(max_length=200,
                                 help_text='Enter last name')
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone_number = models.CharField(max_length=50,
                                    help_text='Enter phone number')

    def get_absolute_url(self):
        return reverse('client-detail', args=[str(self.id)])

    def __str__(self):
        return '{0}, {1}'.format(self.first_name, self.last_name)


class Post(models.Model):
    title = models.CharField(max_length=255, blank=False)
    short_description = models.TextField(blank=False)
    description = models.TextField(blank=False)
    image = models.ImageField(upload_to="static/images/posts/")

    def __str__(self):
        return self.title


class Review(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

repair/shop/forms.py
from django import forms
from .models import Usluga, Review


class UslugaForm(forms.ModelForm):
    class Meta:
        model = Usluga
        fields = ['title', 'author', 'description', 'image', 'genre', 'cost']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('content',)

repair/shop/views.py
import requests
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseNotFound
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect

from cart.forms import CartAddUslugaForm
from .forms import UslugaForm, ReviewForm
from .models import Usluga, Genre, Author, Post, Review


def usluga_list(request, usluga_genre_name=None):
    genre = None
    genres = Genre.objects.all()
    uslugas = Usluga.objects.all()
    sort_t = request.GET.get('sort')

    if (usluga_genre_name):
        genre_ = get_object_or_404(Genre, name=usluga_genre_name)
        uslugas = uslugas.filter(genre=genre_)

    if (str(sort_t) == 'ascending'):
        uslugas = uslugas.order_by('cost')
    elif (str(sort_t) == 'descending'):
        uslugas = uslugas.order_by('-cost')
    elif (str(sort_t) == 'ascendingcount'):
        uslugas = uslugas.order_by('purchase_count')
    elif (str(sort_t) == 'descendingcount'):
        uslugas = uslugas.order_by('-purchase_count')
    return render(request,
                  'shop/usluga/list.html',
                  {'genre': genre, 'genres': genres, 'uslugas': uslugas})


def usluga_detail(request, id):
    usluga = get_object_or_404(Usluga, id=id)
    cart_usluga_form = CartAddUslugaForm()

    joke = requests.get('https://official-joke-api.appspot.com/jokes/programming/random').json()[0]

    return render(request,
                  'shop/usluga/detail.html',
                  {'usluga': usluga, 'cart_usluga_form': cart_usluga_form,
                   'joke': joke['setup'] + joke['punchline']})


def usluga_create(request):
    if not request.user.is_staff:
        raise PermissionDenied("Net dostupa")

    print(1234567)

    form = UslugaForm()

    if request.method == "POST":
        usluga = Usluga.objects.create(title=request.POST.get('title'),
                                       author=Author.objects.get(id=request.POST.get('author')),
                                       cost=request.POST.get('cost'),
                                       genre=Genre.objects.get(id=request.POST.get('genre')),
                                       quantity=0,
                                       description=request.POST.get('description'),
                                       image=request.POST.get('image'))

        usluga.save()
    else:
        return render(request, "shop/usluga/create.html", {"form": form})
    return HttpResponseRedirect("/")


# изменение данных в бд
def usluga_edit(request, id):
    if not request.user.is_staff:
        raise PermissionDenied("Net dostupa")

    try:
        usluga = Usluga.objects.get(id=id)

        form = UslugaForm(initial={'title': usluga.title, 'author': usluga.author,
                                   'cost': usluga.cost, 'genre': usluga.genre,
                                   'description': usluga.description, 'image': usluga.image})

        if request.method == "POST":
            usluga.title = request.POST.get('title')
            print(request.POST.get('title'))
            usluga.author = Author.objects.get(id=request.POST.get('author'))
            usluga.cost = request.POST.get('cost')
            usluga.genre = Genre.objects.get(id=request.POST.get('genre'))
            usluga.quantity = 0
            usluga.description = request.POST.get('description')
            usluga.image = request.FILES.get('image')
            usluga.save()
            return HttpResponseRedirect("/")
        else:
            return render(request, "shop/usluga/edit.html", {"usluga": usluga, 'form': form})
    except usluga.DoesNotExist:
        return HttpResponseNotFound("<h2>usluga not found</h2>")


# удаление данных из бд
def usluga_delete(request, id):
    if not request.user.is_staff:
        raise PermissionDenied("Net dostupa")

    try:
        usluga = Usluga.objects.get(id=id)
        usluga.delete()
        return HttpResponseRedirect("/")
    except usluga.DoesNotExist:
        return HttpResponseNotFound("<h2>usluga not found</h2>")


def review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('shop/reviews.html')
    else:
        form = ReviewForm()

    reviews = Review.objects.all()
    current_user = request.user
    return render(request, 'shop/reviews.html', {'form': form, 'reviews': reviews, 'current_user': current_user})


def news_show(request, id):
    post = get_object_or_404(Post, id=id)
    return render(request, 'shop/news_show.html', {'post': post})


def news(request):
    lst = Post.objects.all()
    return render(request, 'shop/news.html', context={'news_list': lst})


def about(request):
    return render(request, 'shop/about.html')


def policy(request):
    return render(request, 'shop/policy.html')


def vacancies(request):
    return render(request, 'shop/vacancies.html')


def coupons(request):
    return render(request, 'shop/coupons.html')


def faq(request):
    return render(request, 'shop/faq.html')

repair/shop/templates/shop/about.html
{% extends "shop/base.html" %}

{% block content %}

    <section class="info__section">
        <div class="container">
            <h1 class="info__title">О нас</h1>
            <p class="text-fragment capitalized-text">
                <dfn title="Clothes repair">Clothes repair</dfn> - some definition lorem ipsum. <br>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
                deserunt mollit anim id est laborum.
            </p>
        </div>
    </section>

    <section class="video__section">
        <div class="container">
            <h1 class="video__title">Company Video</h1>
            <iframe width="800" height="600" src="https://www.youtube.com/embed/enH2igVo55U"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    allowfullscreen>
            </iframe>
        </div>
    </section>

    <section class="logo__section">
        <div class="container">
            <h1 class="logo__title">Logo</h1>
            <div class="logo-img__wrapper">
                <img src="../media/static/ico.png" alt="logo">
            </div>
        </div>
    </section>

    <section class="audio__section">
        <div class="container">
            <h1 class="audio__title">Soundtrack</h1>
            <audio controls>
                <source src="../../../media/Wag The Dog.mp3" type="audio/mpeg"/>
                <p>
                    Ваш браузер не поддерживает HTML5 аудио. Вот взамен
                    <a href="../../../media/Wag The Dog.mp3">ссылка на аудио</a>
                </p>
            </audio>
        </div>
    </section>

    <section class="history__section">
        <div class="container">
            <h1 class="history__title">Company History</h1>
            <ul class="history__list">
                <li class="history__item">
                    <h2 class="history-item__title">2009</h2>
                    <p class="text-fragment">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
                        tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
                        voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
                        non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </li>

                <li class="history__item">
                    <h2 class="history-item__title">2011</h2>
                    <p class="text-fragment">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
                        tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
                        voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
                        non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </li>

                <li class="history__item">
                    <h2 class="history-item__title">2015</h2>
                    <p class="text-fragment">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
                        tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
                        voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
                        non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </li>

                <li class="history__item">
                    <h2 class="history-item__title">2020</h2>
                    <p class="text-fragment">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
                        tempor incididunt ut
                        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
                        voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
                        non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </li>
            </ul>
        </div>
    </section>

    <section class="certificate__section">
        <div class="container">
            <div class="certificate-container">
                <div class="certificate-border"></div>
                <h1 class="certificate-title">Сертификат Clothes repair</h1>
                <p class="certificate-text">Сертификат подтверждает, что данная компания предоставляет услуги
                    грузоперевозок на высоком уровне, соблюдает все стандарты и нормы, связанные с безопасностью и
                    качеством предоставляемых услуг.
                </p>

                <div class="certificate-confirmation">
                    <h2>Подтверждение Сертификации</h2>
                    <p>Настоящим подтверждаем, что компания "Clothes repair" успешно прошла все необходимые процедуры и
                        требования, для получения данного Сертификата.
                    </p>
                </div>

                <div class="certificate-description">
                    <h2>Описание Сертификата</h2>
                    <ul>
                        <li>Качество предоставляемых услуг грузоперевозок</li>
                        <li>Соблюдение стандартов безопасности</li>
                        <li>Эффективность управления грузовыми операциями</li>
                    </ul>
                </div>

                <div class="certificate-dates">
                    <p>Дата Выдачи</p>
                    <p>14 сентября 2023 года</p>
                    <p>Срок Действия</p>
                    <p>14 сентября 2026 года</p>
                </div>

                <div class="certificate-signature">
                    <p>Подпись и печать уполномоченного лица</p>
                    <div>
                        <p>Джон Доу</p>
                        <p>Директор по сертификации</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <blockquote class="russian">
        Это цитата на русском языке.
        {{ quote }}
    </blockquote>
    <br>

    <blockquote class="english">
        This is a quote in English.
        {{ quote }}
    </blockquote>

{% endblock %}

repair/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Clothes repair{% endblock %}</title>
    <link rel="shortcut icon" href="../media/static/ico.png"/>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/faq.css' %}">
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
    <link rel="stylesheet" href="{% static 'css/reviews.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/news.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,700;1,300&family=Roboto:ital,wght@0,400;0,500;0,700;1,300&display=swap"
          rel="stylesheet">
</head>

<body>

<div class="wrapper">
    <header class="header">
        <a href="/" class="header-brand">Clothes repair</a>

        <nav class="navbar">
            <ul class="navbar-menu">
                <li class="nav-item">
                    <a class="nav-link" href="/about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/coupons">Coupons</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/faq">FAQ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/news">News</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/policy">Policy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/reviews">Reviews</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/vacancies">Vacancies</a>
                </li>
            </ul>
        </nav>
    </header>
</div>

<section class="partners__section">
    <div class="container">
        <h2 class="partners__title">Наши партнеры</h2>
        <div class="partners__list">
            <a class="partners-list__item" href="#">
                <img src="../../../media/merc.png" alt="mercedes" class="partners-item__img">
                <div class="partners-item__subtitle">Mercedes</div>
            </a>
            <a class="partners-list__item" href="#">
                <img src="../../../media/bmv.png" alt="bmw" class="partners-item__img">
                <div class="partners-item__subtitle">BMW</div>
            </a>
            <a class="partners-list__item" href="#">
                <img src="../../../media/chev.jpg" alt="chevrolet" class="partners-item__img">
                <div class="partners-item__subtitle">Chevrolet</div>
            </a>
        </div>
    </div>
</section>

<p>Date <span id="date"></span></p>
<p>Time <span id="time"></span></p>
<p>Time zone <span id="zone"></span></p>

<script>
    const today = new Date();
    const yyyy = today.getFullYear();
    let mm = today.getMonth() + 1; // Months start at 0!
    let dd = today.getDate();
    let h = today.getHours();
    if (h < 10)
        h = '0' + h;
    let min = today.getMinutes();
    if (min < 10)
        min = '0' + min;
    let sec = today.getSeconds();
    if (sec < 10)
        sec = '0' + sec;

    if (dd < 10) dd = '0' + dd;
    if (mm < 10) mm = '0' + mm;

    let formattedToday = dd + '/' + mm + '/' + yyyy;
    let time = h + ":" + min + ":" + sec;
    let tz = -(new Date().getTimezoneOffset() / 60);
    if (tz > 0) {
        tz = "+" + tz;
    }
    tz = "UTC" + tz;
    document.getElementById('date').innerHTML = formattedToday;
    document.getElementById('time').innerHTML = time;
    document.getElementById('zone').innerHTML = tz;


    function toggleUserInfo() {
        var userInfo = document.getElementById('userInfo');
        userInfo.style.display = userInfo.style.display === 'block' ? 'none' : 'block';
    }

    let menuBtn = document.querySelector('.user-toggle');
    let menu = document.querySelector('.user-info__list');
    let burgerMenu = document.querySelector('#burger-menu');
    menuBtn.addEventListener('click', function () {
        menu.classList.toggle('active');
        menuBtn.classList.toggle('active');
        burgerMenu.classList.toggle('active');
    })


    // Получаем ссылки на кнопку открытия модального окна и само модальное окно
    const openModalButton = document.getElementById('openModalBtn');
    const modal = document.getElementById('exampleModal');
    const closeModalButton = document.getElementById('btn-close-modal');

    // Функция открытия модального окна
    function openModal() {
        modal.style.display = 'block';
    }

    // Функция закрытия модального окна
    function closeModal() {
        modal.style.display = 'none';
    }

    // Назначаем обработчики событий на кнопку открытия и закрытия модального окна
    openModalButton.addEventListener('click', openModal);
    closeModalButton.addEventListener('click', closeModal);
    modal.addEventListener('click', function (event) {
        if (event.target === modal) {
            closeModal();
        }
    });

    // обработчик события на нажатие клавиши Escape для закрытия модального окна
    document.addEventListener('keydown', function (event) {
        if (event.key === 'Escape') {
            closeModal();
        }
    });
</script>

<div id="subheader">
    <div class="cart">
        {% if user.is_authenticated %}
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Your cart:
                    <a href="{% url 'cart:cart_detail' %}">
                        {{ total_items }} item{{ total_items|pluralize }},
                        ${{ cart.get_total_price }}
                    </a>
                {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
        {% endif %}
        {% if user.is_authenticated %}
            |{{ user.username }}|
            <a href="{% url 'login:logout' %}">Выйти</a>
        {% else %}
            <a href="{% url 'login:login' %}">Войти</a>
            <a href="{% url 'login:register' %}">Регистрация</a>
        {% endif %}
    </div>
</div>

<div id="content">
    {% block content %}
    {% endblock %}
</div>


<footer>
    <p>&copy; 2006 Clothes repair</p>
</footer>

</body>
</html>

repair/shop/templates/shop/coupons.html
{% extends "shop/base.html" %}

{% block content %}
    <section class="coupons__section">
        <div class="container">
            <ul class="coupons__list d-flex flex-wrap">
                <li class="coupon__item">
                    <h2 class="coupon-item__title">СКИДКА15</h2>
                    <p>Скидка 15% на ремонт обуви</p>
                    <p>Срок действия: до 31 декабря 20XX</p>
                </li>

                <li class="coupon__item">
                    <h2 class="coupon-item__title">КУПОН10</h2>
                    <p>Дополнительная скидка 10% на ремонт одежды</p>
                    <p>Срок действия: до 30 ноября 20XX</p>
                </li>

                <li class="coupon__item">
                    <h2 class="coupon-item__title">СПЕЦИАЛЬНЫЙ5</h2>
                    <p>Скидка 5% на ремонт обуви (архив)</p>
                    <p>Срок действия истек: 15 сентября 20XX</p>
                </li>

                <li class="coupon__item">
                    <h2 class="coupon-item__title">КОД20OFF</h2>
                    <p>Скидка 20% на ремонт одежды (архив)</p>
                    <p>Срок действия истек: 31 августа 20XX</p>
                </li>
            </ul>
        </div>
    </section>
{% endblock %}

repair/shop/templates/shop/faq.html
{% extends "shop/base.html" %}

{% block content %}
    <section class="faq__section">
        <div class="container">
            <h1 class="faq__title">
                <abbr title="Frequently Asked Questions">FAQ</abbr>
            </h1>

            <div class="faq__list">
                <details class="faq__item">
                    <summary>Что такое полная подошва?</summary>
                    <p>Полная подошва - это замена подошвы обуви, включая переднюю и заднюю части. Это необходимо, когда
                        подошва
                        сильно износилась и требует полной замены.</p>
                    <p>Добавлено на сайт: 10 сентября 20XX</p>
                </details>

                <details class="faq__item">
                    <summary>Какие материалы используются при ремонте обуви?</summary>
                    <p>При ремонте обуви могут использоваться различные материалы, включая кожу, замшу, резину и
                        текстиль. Выбор
                        материала зависит от типа обуви и характера повреждений.</p>
                    <p>Добавлено на сайт: 5 августа 20XX</p>
                </details>

                <details class="faq__item">
                    <summary>Какие основные навыки требуются для ремонта одежды?</summary>
                    <p>Для успешного ремонта одежды полезны навыки шитья, умение обращаться с иглой и ниткой,
                        понимание различных методов закрепления и восстановления ткани.</p>
                    <p>Добавлено на сайт: 5 августа 20XX</p>
                </details>

                <details class="faq__item">
                    <summary>Какие типичные проблемы одежды могут быть решены путем ремонта?</summary>
                    <p>Ремонт одежды может решить такие проблемы, как порванные швы, оторванные пуговицы,
                        износ манжет, потертости на ткани, испорченные молнии и многое другое.</p>
                    <p>Добавлено на сайт: 5 августа 20XX</p>
                </details>

                <details class="faq__item">
                    <summary>Каковы некоторые простые ремонтные задачи, которые можно выполнить самостоятельно?</summary>
                    <p>Некоторые простые ремонтные задачи, которые можно выполнить самостоятельно,
                        включают замену пуговиц, починку мелких дырок или разрывов, подшивку подола или ремонт молнии.</p>
                    <p>Добавлено на сайт: 5 августа 20XX</p>
                </details>
            </div>
        </div>
    </section>
{% endblock %}

repair/shop/templates/shop/news.html
{% extends "shop/base.html" %}

{% block content %}

    <section>
        <div class="news__list">
            {% for post in news_list %}
                <article class="news__item">
                    <h2 class="news__title">
                        {{ post.title }}
                    </h2>
                    <p class="news__short_description">
                        {{ post.short_description }}
                    </p>
                    <img src="{{ post.image.url }}" , alt="post_image">
                    <br>
                </article>

                <form method="get" action="news_show/{{ post.id }}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">ЧИТАТЬ ДАЛЕЕ</button>
                </form>
            {% endfor %}
        </div>
    </section>

{% endblock %}

repair/shop/templates/shop/news_show.html
{% extends "shop/base.html" %}

{% block content %}

<section class="news-detail__section">
    <div class="container">
        <img src="{{ post.image.url }}" alt="{{ post.title }}">
        <a href="{{ post.image.url }}" download>Скачать изображение новости</a>
        <p class="news-detail__text">{{ post.description }}</p>
    </div>
</section>

{% endblock %}

repair/shop/templates/shop/policy.html
{% extends "shop/base.html" %}

{% block content %}

 <!-- Содержание политики конфиденциальности -->
 <section id="privacy-policy">
    <h2>1. Введение</h2>
    <p>Добро пожаловать на страницу политики конфиденциальности компании "Стильный Ремонт".</p>
    
    <h2>2. Сбор информации</h2>
    <p>Мы собираем информацию, которую вы предоставляете нам при оформлении заказа на ремонт обуви и одежды. Эта информация может включать ваше имя, контактные данные и детали заказа.</p>
    
    <h2>3. Использование информации</h2>
    <p>Собранная нами информация используется для обработки и выполнения ваших заказов, а также для связи с вами по вопросам, касающимся заказов и услуг компании "Стильный Ремонт".</p>
    
    <h2>4. Защита информации</h2>
    <p>Мы принимаем меры для защиты вашей личной информации и обеспечиваем ее конфиденциальность. Мы не передаем вашу информацию третьим лицам без вашего согласия.</p>
    
    <h2>5. Согласие с политикой конфиденциальности</h2>
    <p>Используя сайт компании "Стильный Ремонт" и оформляя заказы, вы соглашаетесь с нашей политикой конфиденциальности.</p>
    
    <h2>6. Свяжитесь с нами</h2>
    <p>Если у вас есть вопросы или требуется дополнительная информация о нашей политике конфиденциальности, свяжитесь с нами по следующим контактам:</p>
    <address>
        <p>Адрес: Город, Улица, Дом</p>
        <p>Телефон: +7 (123) 456-78-90</p>
        <p>Email: privacy@stylishrepair.com</p>
    </address>
</section>

{% endblock %}